[main]
# catalog prefix, can be empty
# prefix =
prefix = AMG

# include the game store in catalog entries
# with: "AMG Steam: foobar"
# without: "AMG: foobar"
# store_prefix = no
store_prefix = yes

[Windows Store]
enabled = false