[currency]
# This section defines the currency output format and behavior

# Currency mode
# * Accepted values (without quotes):
#   * "on"
#     Currency formatted value will always be appended to the list of results,
#     regardless of the type of the result from the evaluated expression.
#   * "float"
#     Currency formatted value will be appended to the list of results, if and
#     only if the result from the evaluated expression is a floating point
#     value.
#     This can limit output noise in SOME cases if you frequently use this
#     plugin only to convert integers for example.
#   * "off"
#     "Currency" feature is off and no additional formatted value will be
#     appended to the list of result.
# * Default: float
mode = float

# The format to use to display the result
# * Accepted values (without quotes):
#   * "system"
#     Ask the system to format the value. That makes use of your current
#     regional system settings.
#   * "manual"
#     Use the settings below to format the value.
#     This mode is quite limited compared to the countless possible combinations
#     of system configurations, but it allows a constant behavior across several
#     machines in case you use Keypirinha on a USB stick for example.
#format = system

# The character to use as a decimal mark
# * Value must not be empty and does not have to be quoted.
# * Default: "." (dot)
#decimal_separator = "."

# The character to use as a thousand separator
# * Value may be empty and does not have to be quoted.
# * Default: "," (comma)
#thousand_separator = ","

# The number of digits to display after the decimal separator (rounding
# precision).
# * Must be an integer in the range [0, 5]
# * Default: 2
#places  = 2