[home]
# The "home" feature allows you to get quick access to your favorite(s)
# folder(s) by typing a given "trigger" of your choice.

# The string that triggers the "home" listing.
# * This setting allows to specify an arbitrary string that triggers the "home"
#   listing.
# * It can be a single character or a string (case-insensitive).
# * Specify an empty value disables the "home" feature.
# * Default: ~
trigger = .

# Your "home" folders.
# * By default (empty value), it points to the PROFILE directory of the current
#   user. This is equivalent to the following values on default Windows setups:
#     home = ::{5e6c858f-0e22-4760-9afe-ea3317b67173}
#     home = ${env:PROFILEDIR}
#     home = ${env:SYSTEMDRIVE}\Users\${env:USERNAME}
# * Multiline: this setting accepts a multiline value. You can specify several
#   "home" directories, in which case, they will be listed (in order), once
#   you have typed the trigger string.
# * Each line must point to the path of a folder.
#   The folder does not have to exist yet.
# * Example